### ISSUE TITLE
How to implement method pgettext?

### ISSUE THREAD

**Issue by Zaszczyk** [perchlayer/xgettext-webird#2]
I've implemented method pgettext() in my gettext adapter and I would like to Poedit recognize pgettext() in .volt files. I've added this keyword in Catalogoue->Properties->Keywords, it works for *.php file only, it doesn't work for *.volt. 

Should I add something extra to extractor's settings or somewhere else?

**Comment by dschissler** [comment]
Try asking over in the umbrella project for all of the template parsers: https://github.com/gmarty/xgettext

**Comment by dschissler** [comment]
Also I recommend using their package instead of `xgettext-webird`.  This package was only maintained for a short period when I was trying to advance my Volt parser for inclusion into `xgettext-template`.  I have more time now so I will work on a strategy to get people off from using this package and future Volt issues should be made too the [gettext-volt](https://github.com/perchlayer/gettext-volt) repo.

**Comment by Zaszczyk** [comment]
ok, thanks!
